version: '3.7'

services:
    postgres:
        image: postgres:latest
        ports:
            - "${PSQL_PORT}:5432"
        environment:
#            POSTGRES_USER: ${PSQL_USER}
#            POSTGRES_PASSWORD: ${PSQL_PASSWORD}
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "root"
            POSTGRES_DB: ${PSQL_DB}
#        volumes:
#            - ./postgres-data:/var/lib/postgresql/data
    nats-streaming:
        image: nats-streaming:latest
        ports:
            - "${NATS_PORT}:4222"
            - "${NATS_MONITOR_PORT}:8222"
        command: -p 4222 -m 8222
